project_id = "texnkijwcygodtywgedm"

[functions.transcribe]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.validate-google-play-receipt]
verify_jwt = true

[functions.validate-apple-receipt]
verify_jwt = true

[functions.unified-subscription]
verify_jwt = true

[functions.google-analytics-data]
verify_jwt = false

[functions.chat-completion]
verify_jwt = true

[functions.reset-monthly-usage]
verify_jwt = false

[functions.connection-token]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.dynamic-manifest]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.execute-ai-function]
verify_jwt = true