project_id = "texnkijwcygodtywgedm"

[functions.realtime-chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.validate-google-play-receipt]
verify_jwt = true

[functions.validate-apple-receipt]
verify_jwt = true

[functions.unified-subscription]
verify_jwt = true

[functions.google-analytics-data]
verify_jwt = false