# Nixpacks configuration for Fast Now Zenith
# Force Node.js provider to prevent Deno misdetection from Supabase Edge Functions
providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]