# Nixpacks configuration for Fast Now Zenith

providers = ["node"]

[variables]
NODE_ENV = "production"
NODE_VERSION = "18"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist -l 8080 --single"