-- Populate fasting hours data for hours 48-72 with comprehensive information
INSERT INTO fasting_hours (
  hour, stage, metabolic_changes, physiological_effects, mental_emotional_state, 
  benefits_challenges, content_snippet, content_rotation_data, title, body_state, 
  day, phase, difficulty
) VALUES 
  (48, '48‑hour milestone', 'Two days in, insulin sensitivity generally improves. Inflammatory signaling may be lower. The endocrine picture is ''low‑insulin, low‑IGF‑1, high‑fat‑use''.', 'Hour 48: Gut is quiet; gastric acid and enzymes are at rest. Electrolytes matter more now—add a pinch of salt to water if headaches appear.', ARRAY['Satisfaction from progress can boost mood; plan something relaxing tonight', 'If you wake early, low‑intensity movement the next day often restores sleep pressure'], 'Benefit: Noticeable insulin‑sensitivity and appetite control.\nChallenge: Sleep can be light—prioritize wind‑down and magnesium if appropriate.', 'Hour 48: 48‑hour milestone — fat‑burn rises, insulin stays low, and focus gets steadier.', '{"current_index": 0, "variants": [{"type": "metabolic", "content": "Two days in, insulin sensitivity generally improves. Inflammatory signaling may be lower. The endocrine picture is ''low‑insulin, low‑IGF‑1, high‑fat‑use''."}, {"type": "physiological", "content": "Hour 48: Gut is quiet; gastric acid and enzymes are at rest. Electrolytes matter more now—add a pinch of salt to water if headaches appear."}, {"type": "mental", "content": "Satisfaction from progress can boost mood; plan something relaxing tonight. If you wake early, low‑intensity movement the next day often restores sleep pressure"}, {"type": "benefits", "content": "Benefit: Noticeable insulin‑sensitivity and appetite control.\\nChallenge: Sleep can be light—prioritize wind‑down and magnesium if appropriate."}, {"type": "snippet", "content": "Hour 48: 48‑hour milestone — fat‑burn rises, insulin stays low, and focus gets steadier."}]}', '48‑hour milestone', 'Hour 48: Gut is quiet; gastric acid and enzymes are at rest. Electrolytes matter more now—add a pinch of salt to water if headaches appear.', 2, '48_hour_milestone', 'moderate'),
  
  (49, 'Day 3: maintenance on ketones', 'Your brain is comfortable on ketones; glucose needs are mostly covered by the liver. Thyroid T3 may tick down slightly as a normal conservation signal.', 'Hour 49: You''re running comfortably on internal fuel. Some people notice cooler hands/feet as the body conserves heat.', ARRAY['Clarity continues, though patience for stress might be lower', 'Once your body switches to fat, the brain runs smoothly on ketones and glucose made by the liver'], 'Benefit: Very stable energy and calm mind.\nChallenge: Training intensity must stay modest; protect joints.', 'Hour 49: Day 3: maintenance on ketones — fat‑burn rises, insulin stays low, and focus gets steadier.', '{"current_index": 0, "variants": [{"type": "metabolic", "content": "Your brain is comfortable on ketones; glucose needs are mostly covered by the liver. Thyroid T3 may tick down slightly as a normal conservation signal."}, {"type": "physiological", "content": "Hour 49: You''re running comfortably on internal fuel. Some people notice cooler hands/feet as the body conserves heat."}, {"type": "mental", "content": "Clarity continues, though patience for stress might be lower. Once your body switches to fat, the brain runs smoothly on ketones and glucose made by the liver"}, {"type": "benefits", "content": "Benefit: Very stable energy and calm mind.\\nChallenge: Training intensity must stay modest; protect joints."}, {"type": "snippet", "content": "Hour 49: Day 3: maintenance on ketones — fat‑burn rises, insulin stays low, and focus gets steadier."}]}', 'Day 3: maintenance on ketones', 'Hour 49: You''re running comfortably on internal fuel. Some people notice cooler hands/feet as the body conserves heat.', 3, 'day_3_maintenance_on_ketones', 'moderate'),
  
  (72, 'Approach re‑feed', 'Hormones are primed for a careful return to eating: insulin sensitivity is higher, and the gut is resting. Keep mTOR suppressed until re‑feed to maximize cleanup benefits.', 'Hour 72: Prepare the gut: plan a small, protein‑forward, low‑sugar first meal; chew well and eat slowly. Avoid a sudden carb flood to prevent discomfort.', ARRAY['Anticipation can spike cravings; review your re‑feed plan to stay calm and intentional', 'Once your body switches to fat, the brain runs smoothly on ketones and glucose made by the liver'], 'Benefit: Strong appetite control going into re‑feed.\nChallenge: Avoid a large sugar hit first; reintroduce food gradually.', 'Hour 72: Approach re‑feed — fat‑burn rises, insulin stays low, and focus gets steadier.', '{"current_index": 0, "variants": [{"type": "metabolic", "content": "Hormones are primed for a careful return to eating: insulin sensitivity is higher, and the gut is resting. Keep mTOR suppressed until re‑feed to maximize cleanup benefits."}, {"type": "physiological", "content": "Hour 72: Prepare the gut: plan a small, protein‑forward, low‑sugar first meal; chew well and eat slowly. Avoid a sudden carb flood to prevent discomfort."}, {"type": "mental", "content": "Anticipation can spike cravings; review your re‑feed plan to stay calm and intentional. Once your body switches to fat, the brain runs smoothly on ketones and glucose made by the liver"}, {"type": "benefits", "content": "Benefit: Strong appetite control going into re‑feed.\\nChallenge: Avoid a large sugar hit first; reintroduce food gradually."}, {"type": "snippet", "content": "Hour 72: Approach re‑feed — fat‑burn rises, insulin stays low, and focus gets steadier."}]}', 'Approach re‑feed', 'Hour 72: Prepare the gut: plan a small, protein‑forward, low‑sugar first meal; chew well and eat slowly. Avoid a sudden carb flood to prevent discomfort.', 3, 'approach_re_feed', 'challenging')
ON CONFLICT (hour) DO UPDATE SET
  stage = EXCLUDED.stage,
  metabolic_changes = EXCLUDED.metabolic_changes,
  physiological_effects = EXCLUDED.physiological_effects,
  mental_emotional_state = EXCLUDED.mental_emotional_state,
  benefits_challenges = EXCLUDED.benefits_challenges,
  content_snippet = EXCLUDED.content_snippet,
  content_rotation_data = EXCLUDED.content_rotation_data,
  title = EXCLUDED.title,
  body_state = EXCLUDED.body_state,
  day = EXCLUDED.day,
  phase = EXCLUDED.phase,
  difficulty = EXCLUDED.difficulty;