name: Build Android AAB

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Create keystore.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > keystore.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
        echo "storeFile=keystore/my-upload-key.keystore" >> keystore.properties
    
    - name: Build AAB
      run: ./gradlew bundleRelease
    
    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/bundle/release/app-release.aab
